# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


a01= User.create!({:email => "equipo01@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "01" })
a02= User.create!({:email => "equipo02@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "02" })
a03= User.create!({:email => "equipo03@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "03" })
a04= User.create!({:email => "equipo04@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "04" })
a05= User.create!({:email => "equipo05@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "05" })
a06= User.create!({:email => "equipo06@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "06" })
a07= User.create!({:email => "equipo07@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "07" })
a08= User.create!({:email => "equipo08@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "08" })
a09= User.create!({:email => "equipo09@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "09" })
a10= User.create!({:email => "equipo10@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "10" })
a11= User.create!({:email => "equipo11@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "11" })
a12= User.create!({:email => "equipo12@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "12" })
a13= User.create!({:email => "equipo13@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "13" })
a14= User.create!({:email => "equipo14@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "14" })
a15= User.create!({:email => "equipo15@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "15" })
a16= User.create!({:email => "equipo16@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "16" })
a17= User.create!({:email => "equipo17@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "17" })
a18= User.create!({:email => "equipo18@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "18" })
a19= User.create!({:email => "equipo19@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "19" })
a20= User.create!({:email => "equipo20@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => false, :team => "20" })


b01= User.create!({:email => "staff01@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b02= User.create!({:email => "staff02@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b03= User.create!({:email => "staff03@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b04= User.create!({:email => "staff04@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b05= User.create!({:email => "staff05@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b06= User.create!({:email => "staff06@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b07= User.create!({:email => "staff07@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b08= User.create!({:email => "staff08@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b09= User.create!({:email => "staff09@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b10= User.create!({:email => "staff10@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b11= User.create!({:email => "staff11@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b12= User.create!({:email => "staff12@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b13= User.create!({:email => "staff13@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b14= User.create!({:email => "staff14@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b15= User.create!({:email => "staff15@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b16= User.create!({:email => "staff16@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b17= User.create!({:email => "staff17@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b18= User.create!({:email => "staff18@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b19= User.create!({:email => "staff19@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})
b20= User.create!({:email => "staff20@bootcamp.com", :password => "bootcamp2016", :password_confirmation => "bootcamp2016", :admin => true})